version: "3.7"

networks:
  api-docker.network:
    driver: bridge

services:
  postgres:
    build: ./docker/postgres
    container_name: api_postgres
    tty: true
    restart: always
    networks:
      - api-docker.network
    ports:
      - "5432:5432"
    volumes:
      - "./docker/postgres/dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
